### ISSUE TITLE
安装运行环境运行后报错

### ISSUE THREAD

**Issue by peasshoter** [xushengfeng/eSearch-OCR#1]
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 8 Version 9600 MP (2 procs) Free x64
Product: WinNt, suite: SingleUserTS
Built by: 6.3.9600.17031 (winblue_gdr.140221-1952)
Machine Name:
Debug session time: Mon Jul 11 10:05:04.000 2022 (UTC + 8:00)
System Uptime: not available
Process Uptime: 0 days 0:00:01.000
............................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1c80.1fd8): Unknown exception - code c0000142 (first/second chance not available)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
ntdll!RtlRaiseStatus+0x20:
00007ffb`04c0cdd0 488b85b8000000  mov     rax,qword ptr [rbp+0B8h] ss:00000001`a1ccf3d8=00007ffb04c0cdd0

**Comment by xushengfeng** [comment]
你是要自己编译吗，大部分代码都是源于[Paddle OCR](https://github.com/PaddlePaddle/PaddleOCR)
编译还请看[官方文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/cpp_infer/readme_ch.md)
